spring:
  config:
    import: optional:configtree:/etc/secrets/,optional:configtree:./secrets/

github:
  token: ${GIT_TOKEN}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger.html
    enabled: true
    disable-swagger-default-url: true
    config:
      title: Initializer API
      version: v1


templates:
  starter-list:
    -
      starter: api
      target: api
      paths:
        - starter-api/src/main/java/org/example/api
      application: starter-api/src/main/resources/application.yml
      pom: starter-api/pom.xml
    -
      starter: kafka-consumer
      target: kafka
      paths:
        - starter-kafka/src/main/java/org/example/kafkaconsumer
      application: starter-kafka/src/main/resources/application.yml
      pom: starter-kafka/pom.xml
    -
      starter: kafka-producer
      target: kafka
      paths:
        - starter-kafka/src/main/java/org/example/kafkaproducer
      application: starter-kafka/src/main/resources/application.yml
      pom: starter-kafka/pom.xml
    -
      starter: sql
      target: sql
      paths:
        - starter-sql/src/main/java/org/example/sql
      application: starter-sql/src/main/resources/application.yml
      pom: starter-sql/pom.xml
